from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://web.whatsapp.com/")
    page.get_by_role("button", name="Link with phone number", exact=True).click()
    page.get_by_label("Type your phone number.").click()
    page.get_by_label("Type your phone number.").fill("+254 743 854888")
    page.get_by_role("button", name="Next").click()
    page.goto("https://web.whatsapp.com/")
    page.get_by_label("Open the chat context menu").click()
    page.get_by_label("Exit group").click()
    page.get_by_role("paragraph").click()
    page.get_by_role("textbox", name="Search input textbox").fill("438")
    page.get_by_role("button", name="⊙ (You)").click()
    page.get_by_role("textbox", name="Type a message").get_by_role("paragraph").click()
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi ")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi J")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi James ")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi James T")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi James This is ")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi James This is S")
    page.get_by_role("textbox", name="Type a message").press("CapsLock")
    page.get_by_role("textbox", name="Type a message").fill("Hi James This is Successful")
    page.get_by_role("textbox", name="Type a message").get_by_role("paragraph").click()
    page.locator("div").filter(has_text=re.compile(r"^Hi James This is Successful$")).first.click()
    page.get_by_role("textbox", name="Type a message").press("Control+b")
    page.get_by_role("textbox", name="Type a message").press("Control+z")
    page.get_by_label("Send").click()
    page.get_by_text("JOB VACANCIES 2.").click()
    page.get_by_role("gridcell", name="+254 706 571913 11:58 AM").locator("div").first.click()
    page.get_by_role("textbox", name="Search input textbox").get_by_role("paragraph").click()
    page.get_by_role("textbox", name="Search input textbox").fill("job vacanc")
    page.locator("html").click()
    page.get_by_label("Attach").click()
    page.locator("li").filter(has_text="Document").locator("div").nth(1).click()
    page.get_by_role("contentinfo").get_by_role("application").set_input_files(".minttyrc")
    page.get_by_role("button", name="x-alt").click()
    page.get_by_label("Attach").click()
    page.get_by_text("Photos & videos").click()
    page.get_by_role("contentinfo").get_by_role("application").set_input_files("WIN_20240201_15_53_58_Pro.jpg")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)